name: google_phone_number_hint
description: "A new Flutter plugin to get the phone number hint from Google Play Services."
version: 0.0.1
homepage: "https://github.com/champ96k/google_phone_number_hint"

environment:

  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.example.google_phone_number_hint
        pluginClass: GooglePhoneNumberHintPlugin